"""categories always owned by a user

Revision ID: 0013b5e4bb72
Revises: fe4569cdf769
Create Date: 2026-08-08 18:29:34.448099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0013b5e4bb72'
down_revision = 'fe4569cdf769'
branch_labels = None
depends_on = None


def upgrade():
    # Categorias legadas sem dono (user_id IS NULL) sao atribuidas ao primeiro
    # usuario existente antes do NOT NULL, para nao perder dados historicos.
    op.execute(
        """
        UPDATE categories
        SET user_id = (SELECT id FROM users ORDER BY created_at ASC LIMIT 1)
        WHERE user_id IS NULL
        """
    )

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_categories_replaces_category_id'))
        batch_op.drop_constraint(batch_op.f('categories_replaces_category_id_fkey'), type_='foreignkey')
        batch_op.drop_column('hidden')
        batch_op.drop_column('replaces_category_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('replaces_category_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hidden', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('categories_replaces_category_id_fkey'), 'categories', ['replaces_category_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_categories_replaces_category_id'), ['replaces_category_id'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###
