"""add quotes table

Revision ID: 1f9c7806cd60
Revises: e5f1b2c3d4a6
Create Date: 2026-08-20 16:11:39.276594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f9c7806cd60'
down_revision = 'e5f1b2c3d4a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('currency', sa.Text(), nullable=False),
    sa.Column('brl_rate', sa.Numeric(precision=14, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('currency')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    # ### end Alembic commands ###
