"""add bill reminders

Revision ID: 7658cd49972d
Revises: a1c9e5f7d3b2
Create Date: 2026-08-08 19:18:51.800751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7658cd49972d'
down_revision = 'a1c9e5f7d3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_reminders',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('current_due_date', sa.Date(), nullable=False),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('last_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['last_transaction_id'], ['transactions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bill_reminders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bill_reminders_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_reminders_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bill_reminders_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_reminders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bill_reminders_user_id'))
        batch_op.drop_index(batch_op.f('ix_bill_reminders_category_id'))
        batch_op.drop_index(batch_op.f('ix_bill_reminders_account_id'))

    op.drop_table('bill_reminders')
    # ### end Alembic commands ###
