"""add paid_amount to credit card invoices

Revision ID: f8ebcc16c295
Revises: 7658cd49972d
Create Date: 2026-08-08 20:19:45.217281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8ebcc16c295'
down_revision = '7658cd49972d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_invoices', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('paid_amount', sa.Numeric(precision=14, scale=2), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_card_invoices', schema=None) as batch_op:
        batch_op.drop_column('paid_amount')

    # ### end Alembic commands ###
