"""add category override and hide support

Revision ID: fe4569cdf769
Revises: e1c90905e104
Create Date: 2026-08-08 17:20:38.117940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe4569cdf769'
down_revision = 'e1c90905e104'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('replaces_category_id', sa.UUID(), nullable=True))
        batch_op.create_index(batch_op.f('ix_categories_replaces_category_id'), ['replaces_category_id'], unique=False)
        batch_op.create_foreign_key(None, 'categories', ['replaces_category_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_categories_replaces_category_id'))
        batch_op.drop_column('replaces_category_id')
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
